// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeIPOfO940gaUMb8pHQTvWEE87HrC6Mfg',
    appId: '1:116477521245:android:2a991c5350cd1de5a30cb4',
    messagingSenderId: '116477521245',
    projectId: 'bloc-login-b0e04',
    storageBucket: 'bloc-login-b0e04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3tDukvmJhu0pV5Dp0JoZOARbMPY4TNU4',
    appId: '1:116477521245:ios:ef4516399b42d2c8a30cb4',
    messagingSenderId: '116477521245',
    projectId: 'bloc-login-b0e04',
    storageBucket: 'bloc-login-b0e04.firebasestorage.app',
    androidClientId: '116477521245-5th3u0sud9vcgkp7rhau17e5snlmbs7u.apps.googleusercontent.com',
    iosClientId: '116477521245-h8slntdjb49oi7114qklq1uptb1v1en5.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );

}